language: android
sudo: false
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - chmod u+x gradlew

notifications:
  email: true