language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - chmod u+x gradlew

script:
  - ./gradlew -v
  - ./gradlew clean --stacktrace
  - ./gradlew build --stacktrace

notifications:
  email: true