language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_install:
  - chmod u+x gradlew

script:
  - ./gradlew -v
  - ./gradlew clean
  - ./gradlew build

notifications:
  email: true