language: android
sudo: false
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25

before_install:
  - chmod u+x gradlew

notifications:
  email: true