language: android

andoroid:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23

  licenses:
   - android-sdk-license-.+

before_install:
  - git submodule update --init --recursive
  - chmod u+x gradlew

  install: true

  after_failure: true

notifications:
  email: true